spring.application.name=gateway
server.port=${PORT:8081}
server.address=0.0.0.0
spring.jpa.open-in-view=false

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:routeops;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
#spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.H2Dialect}

# ? Datasource (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/RouteDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# ? JPA + Hibernate
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#routeops.routing.url=${ROUTEOPS_ROUTING_URL:http://localhost:18080/route}
routeops.routing.url=${ROUTEOPS_ROUTING_URL:http://localhost:18080}
# management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
# spring.jpa.open-in-view=false

application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY:c2VjdXJlX2pkdF9kZWZhdWx0X2tleV8xMjM0NTY3ODk=}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

application.security.geoapify.secret-key=${APPLICATION_SECURITY_GEOAPIFY_SECRET_KEY}
application.security.openrouteservice.secret-key=${APPLICATION_SECURITY_OPENROUTESERVICE_SECRET_KEY}
application.security.mapbox.secret-key=${APPLICATION_SECURITY_MAPBOX_SECRET_KEY}

debug=false
#debug=true

# CORS Configuration (nginx handles preflight, backend allows all origins)
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true
spring.main.lazy-initialization=true
spring.jpa.defer-datasource-initialization=true
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=3

#Front end URI
routeOps.frontend.url=${ROUTEOPS_FRONTEND_URL:http://localhost:4200}